---
- hosts: 172.31.27.213
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy static file into ansible node
    copy:
     src: mytestfile
     dest: /home/ubuntu/mystaticfile

  - name: download internet files into node
    get_url:
       url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
       dest: /home/ubuntu/jenkins.war
       force_basic_auth: yes
  handlers:
  - name: startwebserver
    service:
      name: apache2
      state: started

  