---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks: 
  - name: install java on ubuntu node
    apt:
      name: "{{myjavapackubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: install java on amazon nodes
    yum:
     name: "{{myjavapackredhat}}" 
     state: present
    when: ansible_os_family=="RedHat"
  

  
  