---
- hosts: 172.31.27.213
  become: yes
  tasks: 
  - name: install webserver on ubuntu node
    apt:
      name: {{mywebserverpackubuntu}}
      state: present
    when: ansiible_os_family=="Debian"
  - name: install java on ubuntu node
    apt:
      name: {{myjavapackubuntu}}
      state: started
    when: ansible_os_family=="Debian"
  
  - name: install webserver on redhat node
    yum: 
     name: {{mywebserverpackredhat}}
     state: present
    when: ansible_os_family=="RedHat"
  - name: install java on redhat node
    yum:
      name: {{myjavapackredhat}}
      state: started
    when: ansible_os_family=="RedHat"
  
  