---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
     name: "{{myubuntupack}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: install httpd on amazon
    yum:
     namr: "{{myamazonpack}}"
     state: present

